version: "3.7"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: curv_development
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: secret
    volumes:
      - ./.postgres:/var/lib/postgresql/data
