version: '3.7'
services:
  api:
    build: .
    ports:
      - 3000:8080
    env_file: .env
    environment:
      - PORT=8080
      - TYPEORM_HOST=db
    depends_on:
      - db
    networks:
      - app
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: curv_development
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: secret
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    driver: bridge
